### ISSUE TITLE
Blanks in object names

### ISSUE THREAD

**Issue by robbrucks** [quadewarren/ansible-role-artifactory#17]
I'm running into an issue where an LDAP group DN contains blanks, like this:

cn=test - LDAP,ou=Groups,dc=Mycompany,dc=Com

This results in the following API call being generated by this module:

`GET /artifactory/api/security/groups/test - ldap
`
Which results in an HTTP 400 error from Artifactory.

Can you change the generated URI to embed "%20" for blanks?   Or maybe there's a better solution...

**Comment by quadewarren** [comment]
I don't think spaces should exist in names like that, but it's an obvious corner case I didn't account for. I'll look into urlencode to see if that could solve the issue.

**Comment by robbrucks** [comment]
I didn't think spaces should be there either, but both Active Directory and Artifactory appear to allow them... so 🤷‍♂️

**Comment by quadewarren** [comment]
Issue was resolved with blanks in names. An additional issue was addressed that was discovered during triage that showed that artifactory_group and artifactory_permission names needed to be set to lowercase in order for it to interact successfully with artifactory. Only those two modules were updated with the fix.
