### ISSUE TITLE
repoLayoutRef doesnt show as a change to the configuration

### ISSUE THREAD

**Issue by gregswift** [quadewarren/ansible-role-artifactory#6]
If a repository is configured with one repoLayoutRef, but we change it we would expect ansible to change it but instead we get:

```
"Repo 'bower-remote' was not updated because config was identical."
```

**Comment by quadewarren** [comment]
Looking into why it isn't picking up the config value difference.

**Comment by quadewarren** [comment]
I could not replicate this issue. In our staging area, I was able to update the repoLayoutRef with different values. It even threw a 404 for a layout ref that didn't exist. Could you provide your input to the module?

**Comment by quadewarren** [comment]
No further information on this issue. @gregswift Is this good to close?

**Comment by quadewarren** [comment]
Closing.
